language: go
sudo: false
git:
  depth: 1
notifications:
  email: false

go:
  - "1.13.x"
  - "1.14.x"
  - "tip"

matrix:
  allow_failures:
    - go: tip

script:
  - go vet .
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
